services:
  - type: web
    name: transport-booking-website
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:application
    autoDeploy: true
    envVars:
      - key: FLASK_SECRET_KEY
        sync: false
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASS
        sync: false
      - key: ORS_API_KEY
        sync: false
